
pipeline {
  agent any
  stages {
    stage ("Install App") {
      steps {
        sh "scp -r -o StrictHostKeyChecking=no cloud_user@eaf50fe3021c.mylabserver.com:/home/cloud_user/.kube/config ."
        sh 'kubectl get pods'
      }
    }

}
}
